services:
  app-php:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: scandi-test-php
    restart: always
    working_dir: /var/www
    volumes:
      - ../.:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: scandi-test-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../.:/var/www
      - ./nginx:/etc/nginx/conf.d
  mysql:
    image: mysql:5.6
    restart: always
    container_name: scandi-test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: temppassword
      MYSQL_DATABASE: SCANDI_TEST
